certifi==2022.12.7
charset-normalizer==3.1.0
clickhouse-driver==0.2.5
clickhouse-sqlalchemy==0.2.3
colorlog==6.7.0
greenlet==2.0.2
idna==3.4
prettytable==3.6.0
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
requests==2.28.2
SQLAlchemy==1.4.47
SQLAlchemy-Utils==0.40.0
typing_extensions==4.5.0
tzdata==2022.7
tzlocal==4.3
urllib3==1.26.15
wcwidth==0.2.6
