baostock==0.8.8
beautifulsoup4==4.12.2
bs4==0.0.1
build==0.10.0
certifi==2022.12.7
charset-normalizer==3.1.0
clickhouse-driver==0.2.5
clickhouse-sqlalchemy==0.2.3
colorlog==6.7.0
ginkgo @ file:///home/kaoru/Documents/Ginkgo/dist/ginkgo-0.1.4.tar.gz
greenlet==2.0.2
idna==3.4
lxml==4.9.2
numpy==1.24.2
packaging==23.1
pandas==2.0.0
prettytable==3.6.0
pyproject_hooks==1.0.0
python-dateutil==2.8.2
pytz==2022.7.1
pytz-deprecation-shim==0.1.0.post0
PyYAML==6.0
requests==2.28.2
rpdb==0.1.6
simplejson==3.19.1
six==1.16.0
soupsieve==2.4.1
SQLAlchemy==1.4.47
SQLAlchemy-Utils==0.40.0
tushare==1.2.89
typing_extensions==4.5.0
tzdata==2022.7
tzlocal==4.3
urllib3==1.26.15
wcwidth==0.2.6
websocket-client==0.57.0
