baostock==0.8.8
black==21.11b1
certifi==2021.10.8
charset-normalizer==2.0.8
click==8.0.3
colorlog==6.6.0
cycler==0.11.0
fonttools==4.28.3
ginkgo @ file:///home/kaoru/Documents/Ginkgo/dist/ginkgo-0.1.30.tar.gz
idna==3.3
joblib==1.1.0
kiwisolver==1.3.2
matplotlib==3.5.0
mypy-extensions==0.4.3
numpy==1.21.4
packaging==21.3
pandas==1.3.4
pathspec==0.9.0
Pillow==8.4.0
platformdirs==2.4.0
pymongo==4.0
pyparsing==3.0.6
PyQt5==5.15.7
PyQt5-Qt5==5.15.2
PyQt5-sip==12.11.0
python-dateutil==2.8.2
pytz==2021.3
regex==2021.11.10
requests==2.26.0
scikit-learn==1.0.2
scipy==1.8.0
setuptools-scm==6.3.2
six==1.16.0
threadpoolctl==3.1.0
tomli==1.2.2
torch==1.12.0+cu116
torchaudio==0.12.0+cu116
torchvision==0.13.0+cu116
tqdm==4.62.3
typing_extensions==4.0.1
urllib3==1.26.7
