"""
Ant Design 选择器常量

集中管理 E2E 测试中使用的 CSS 选择器，方便 Ant Design 版本升级时统一更新。
未来计划：在 Vue 组件中添加 data-testid 属性，逐步替换 CSS 类选择器。
"""

# Ant Design 组件选择器
MODAL = ".ant-modal"
MODAL_CONFIRM = ".ant-modal-confirm"
TABLE = ".ant-table"
TABLE_ROW = ".ant-table-row"
TABLE_CELL = ".ant-table-cell"
SELECT = ".ant-select"
SELECT_DROPDOWN = ".ant-select-dropdown"
SELECT_ITEM = ".ant-select-item"
INPUT = ".ant-input"
INPUT_NUMBER = ".ant-input-number"
DATE_PICKER = ".ant-picker"
BTN = ".ant-btn"
BTN_PRIMARY = ".ant-btn-primary"
BTN_DANGER = ".ant-btn-dangerous"
BTN_LINK = ".ant-btn-link"
MENU = ".ant-menu"
MENU_ITEM = ".ant-menu-item"
TABS = ".ant-tabs"
TAB_PANE = ".ant-tabs-tabpane"
FORM_ITEM = ".ant-form-item"
MESSAGE = ".ant-message"
NOTIFICATION = ".ant-notification"
SPIN = ".ant-spin"
DRAWER = ".ant-drawer"
POPUP = ".ant-popover"
TAG = ".ant-tag"
BADGE = ".ant-badge"
SWITCH = ".ant-switch"
CHECKBOX = ".ant-checkbox"
RADIO = ".ant-radio"
DROPDOWN = ".ant-dropdown"
BREADCRUMB = ".ant-breadcrumb"
PAGINATION = ".ant-pagination"
CARD = ".ant-card"
COLLAPSE = ".ant-collapse"
PROGRESS = ".ant-progress"
RESULT = ".ant-result"
EMPTY = ".ant-empty"

# 通用文本选择器
CLOSE_BTN = ".ant-modal-close, [aria-label='Close'], .ant-drawer-close"
SUBMIT_BTN = "button[type='submit'], .ant-btn-primary"
CANCEL_BTN = ".ant-btn-default:not(.ant-btn-primary)"
