# Upstream: Backtest Engines, Portfolio Manager
# Downstream: Data Layer, Event System
# Role: PortfolioT1Backtest回测投资组合管理策略/持仓/资金和执行支持交易系统功能支持相关功能


"""
The `Portfolio` class is responsible for managing the positions and capital for the system.(Backtest and Live)

- Initializing the portfolio with an initial capital amount and a set of securities to track.

- Keeping track of the current positions and cash balance for the portfolio.

- Executing trades based on signals generated by the Strategy.

- Generating reports and metrics related to the performance of the portfolio. The reports also contain charts.
"""

import time
import uuid
import datetime
from rich.console import Console


from typing import List
from decimal import Decimal
from ginkgo.trading.bases.portfolio_base import PortfolioBase
from ginkgo.entities import Bar
from ginkgo.entities import Position
from ginkgo.entities import Signal
from ginkgo.trading.events import (
    EventOrderAck,
    EventOrderPartiallyFilled,
    EventSignalGeneration,
    EventPriceUpdate,
    EventOrderCancelAck,
)

from ginkgo.libs import datetime_normalize, base_repr, to_decimal, GLOG
from ginkgo.interfaces.notification_interface import INotificationService, NotificationServiceFactory
from ginkgo.data.models import MOrder
from ginkgo.enums import (
    DIRECTION_TYPES,
    SOURCE_TYPES,
    ORDERSTATUS_TYPES,
    RECORDSTAGE_TYPES,
)
from ginkgo.data.containers import container


console = Console()


class PortfolioT1Backtest(PortfolioBase):
    # The class with this __abstract__  will rebuild the class from bytes.
    # If not run time function will pass the class.
    __abstract__ = False

    def __init__(self, notification_service: INotificationService = None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 使用依赖注入的通知服务，如果没有提供则自动创建
        self._notification_service = notification_service or NotificationServiceFactory.create_service()
        self._signals: List[Signal] = []  # 存储Signal对象，用于T+1延迟执行
        self._orders = []  # 存储已确认的订单（ACK事件）
        self._filled_orders = []  # 存储已成交的订单（FILLED事件）

    @property
    def signals(self):
        return self._signals

    @property
    def orders(self):
        return self._orders

    @property
    def filled_orders(self):
        return self._filled_orders

    def get_position(self, code: str) -> Position:
        """
        Get Position object from portfolio.
        Args:
            code(str): code
        Returns:
            return POSITION if it exists else return NONE
        """
        if code in self.positions.keys():
            return self.positions[code]
        return None

    def add_position(self, position: Position) -> None:
        """
        重写基类方法，添加持仓并持久化（通过 Service 层）
        """
        # 调用基类方法添加持仓
        super().add_position(position)

        # 记录持仓事件到ClickHouse
        try:
            GLOG.backtest.trade.position(
                symbol=position.code,
                volume=position.volume,
                position_cost=position.cost,
                position_price=position.price,
                portfolio_id=position.portfolio_id,
                engine_id=position.engine_id,
                run_id=position.run_id,
                business_timestamp=self.business_timestamp,
            )
        except Exception as e:
            GLOG.ERROR(f"Failed to log position event: {e}")

        # 将持仓记录保存（通过 Service 层）
        try:
            from ginkgo.data.containers import container
            result_service = container.result_service()
            result_service.create_position_record(
                portfolio_id=position.portfolio_id,
                engine_id=position.engine_id,
                run_id=position.run_id,
                code=position.code,
                cost=position.cost,
                volume=position.volume,
                frozen_volume=position.frozen_volume,
                frozen_money=position.frozen_money,
                price=position.price,
                fee=position.fee,
                timestamp=position.timestamp,
                business_timestamp=self.business_timestamp,
            )
            GLOG.DEBUG(f"Position record saved: {position.code} volume={position.volume}")
        except Exception as e:
            GLOG.ERROR(f"Failed to save position record: {e}")

    def advance_time(self, time: any, *args, **kwargs) -> None:
        """
        时间推进到下一周期
        包含完整的T+1交易制度实现：
        1. 处理T+1结算队列（持仓解冻）
        2. 批量处理延迟信号
        3. 更新投资组合状态
        """
        from ginkgo.libs import datetime_normalize

        new_time = datetime_normalize(time)

        # ===== 步骤1: T+1结算处理 =====
        # 处理所有持仓的结算队列，将到期的冻结持仓转为可用
        settled_positions = 0
        for code, position in self.positions.items():
            initial_settlement_frozen = position.settlement_frozen_volume
            if initial_settlement_frozen > 0:
                position.process_settlement_queue(new_time)
                if position.settlement_frozen_volume < initial_settlement_frozen:
                    settled_positions += 1
                    GLOG.INFO(f"Position {code}: {initial_settlement_frozen - position.settlement_frozen_volume} shares settled, "
                        f"available: {position.volume}, settlement_frozen: {position.settlement_frozen_volume}",
                    )

        if settled_positions > 0:
            GLOG.INFO(f"Processed settlement for {settled_positions} positions")

        # ===== 步骤2: 时间推进和状态更新 =====
        # Go next TimePhase - 统一使用hook机制
        self.update_worth()
        self.update_profit()

        GLOG.INFO("🔧 About to call super().advance_time")
        super().advance_time(time, *args, **kwargs)
        GLOG.INFO("✅ super().advance_time completed")

        # ===== 步骤3: 批处理模式处理 =====
        if self._batch_processing_enabled and self._batch_processor:
            try:
                pending_orders = self.force_process_pending_batches()
                if pending_orders:
                    GLOG.INFO(f"Processed {len(pending_orders)} pending batch orders at day transition")
            except Exception as e:
                GLOG.ERROR(f"Failed to process pending batches during day transition: {e}")

        # ===== 步骤4: T+1信号批量处理 =====
        # 推进到新时间后，批量处理上期的延迟信号
        delayed_signals_count = len(self._signals)
        # 取消详细的Portfolio状态打印以避免性能开销
        # print(f"🕰️ [TIME ADVANCE] Portfolio time advance to {time}: {self}")
        GLOG.INFO(f"🕰️ Portfolio time advance to {time}, {delayed_signals_count} delayed signals")

        if delayed_signals_count > 0:
            GLOG.WARN(f"⚡ [T+1 PROCESSING] Processing {delayed_signals_count} delayed T+1 signals from previous period",
            )
            for i, signal in enumerate(self._signals):
                GLOG.INFO(f"[T1_PROCESSING] #{i+1} Re-publishing {signal.direction.name} {signal.code}")
                e = EventSignalGeneration(signal)
                event_uuid = getattr(e, "uuid", "N/A")[:8]
                signal_uuid = getattr(signal, "uuid", "N/A")[:8]
                print(
                    f"[T1_PUBLISH] #{i+1}/{len(self._signals)} {signal.direction.name} {signal.code} {signal.business_timestamp} Event:{event_uuid} Signal:{signal_uuid} Portfolio:{self.uuid[:8]}"
                )

                self.put(e)

        # Reset past signals
        old_count = len(self._signals)
        self._signals = []

        # ===== 步骤5: ENDDAY钩子（移到T+1信号处理之后）=====
        # 在T+1订单成交后记录净值，确保记录的是收盘后的实际净值
        GLOG.INFO("🔧 About to process ENDDAY analyzer hooks (after T+1 processing)")
        self.update_worth()  # 更新净值（订单成交后的最新值）
        self.update_profit()
        for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.ENDDAY]:
            func(RECORDSTAGE_TYPES.ENDDAY, self.get_info())
        for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.ENDDAY]:
            func(RECORDSTAGE_TYPES.ENDDAY, self.get_info())

        # ===== 步骤5: 新时间状态初始化 =====
        activate_count = len(self._analyzer_activate_hook.get(RECORDSTAGE_TYPES.NEWDAY, []))
        record_count = len(self._analyzer_record_hook.get(RECORDSTAGE_TYPES.NEWDAY, []))
        print(f"[NEWDAY HOOK] activate_count={activate_count}, record_count={record_count}")
        for func in self._analyzer_activate_hook.get(RECORDSTAGE_TYPES.NEWDAY, []):
            if func is not None and callable(func):
                func(RECORDSTAGE_TYPES.NEWDAY, self.get_info())
        for func in self._analyzer_record_hook.get(RECORDSTAGE_TYPES.NEWDAY, []):
            if func is not None and callable(func):
                func(RECORDSTAGE_TYPES.NEWDAY, self.get_info())

    def on_signal(self, event: EventSignalGeneration):
        """
        Dealing with the signal coming.
        支持批处理模式和传统T+1模式
        1. get a signal
        2. after sizer and risk manager
        3.1 drop the signal
        3.2 put order to event engine
        """
        signal_payload = event.payload if hasattr(event, "payload") else None

        # 添加Signal接收的关键事件流日志
        if signal_payload:
            print(
                f"[SIGNAL_RECV] {signal_payload.direction.name} {signal_payload.code} {signal_payload.business_timestamp} Portfolio:{self.uuid[:8]} Signal:{signal_payload.uuid[:8]}"
            )
        else:
            print(f"[SIGNAL_ERROR] Signal payload missing Event:{event.uuid[:8] if hasattr(event, 'uuid') else 'N/A'}")
            return

        def normalize_time_for_comparison(t):
            """标准化时间用于比较，解决时区不匹配问题"""
            if t is None:
                return None
            # 如果有时间信息，转换为UTC时间并去除时区信息，保持datetime对象类型
            if hasattr(t, "tzinfo") and t.tzinfo is not None:
                utc_tuple = t.utctimetuple()
                # 标准化夏令时字段为0，确保一致性
                return utc_tuple[:8] + (0,)  # tm_isdst=0
            # 已经是naive时间，转换为struct_time以保持一致性
            if isinstance(t, datetime.datetime):
                naive_tuple = t.timetuple()
                # 标准化夏令时字段为0，确保一致性
                return naive_tuple[:8] + (0,)  # tm_isdst=0
            # 如果已经是其他时间表示，直接返回
            return t

        current_time = self.get_time_provider().now()

        # Check future event
        if event.business_timestamp and current_time and event.business_timestamp > current_time:
            return

        # Check portfolio setup
        if not self.is_all_set():
            return

        if self._batch_processing_enabled and self._batch_processor:
            try:
                # T+1机制：当天信号延迟到明天处理
                # 注意：批处理模式也需要处理时区问题
                business_time_normalized = normalize_time_for_comparison(event.business_timestamp)
                current_time_normalized = normalize_time_for_comparison(current_time)

                # T+1延迟机制：如果信号时间 >= 当前时间，则延迟到下一个时间点处理
                GLOG.INFO(f"T+1 Decision: business_time={business_time_normalized} >= current_time={current_time_normalized} ? {business_time_normalized >= current_time_normalized}",
                )
                if business_time_normalized >= current_time_normalized:
                    if business_time_normalized > current_time_normalized:
                        GLOG.CRITICAL(f"🚨 [FUTURE TIME] Batch Mode: Future signal from {event.business_timestamp} (current: {current_time}), delaying to next period.")
                    else:
                        GLOG.INFO(f"T+1 Batch Mode: delaying current day signal {event.code} to next period. {current_time}",
                        )
                    self._signals.append(event.payload)
                    GLOG.INFO(f"Signal added to _signals queue. Total signals: {len(self._signals)}")
                    return

                # 使用批处理感知的信号处理
                self._batch_aware_on_signal(event)
                return

            except Exception as e:
                GLOG.ERROR(f"Batch signal processing failed, falling back to traditional mode: {e}")
                # 继续执行传统处理逻辑

        # 传统T+1处理逻辑
        # T+1, Order will send after 1 day that signal comes.
        # 注意：时间比较需要处理时区问题，将两个时间都转换为UTC或naive时间
        business_time_normalized = normalize_time_for_comparison(event.business_timestamp)
        current_time_normalized = normalize_time_for_comparison(current_time)

        GLOG.INFO(f"=== T+1 TIME COMPARISON DEBUG ===")
        GLOG.INFO(f"event.business_timestamp: {event.business_timestamp}")
        GLOG.INFO(f"current_time from time_provider: {current_time}")
        GLOG.INFO(f"normalized business_time: {business_time_normalized}")
        GLOG.INFO(f"normalized current_time: {current_time_normalized}")
        GLOG.INFO(f"Are they equal after normalization? {business_time_normalized == current_time_normalized}")
        GLOG.INFO(f"=====================================")
        GLOG.INFO(f"T+1 CHECK: business_time >= current_time? {business_time_normalized >= current_time_normalized}"
        )

        # T+1延迟机制：如果信号时间 >= 当前时间，则延迟到下一个时间点处理
        # 这确保只有过去的信号才会被立即处理，当天和未来的信号都会被延迟
        if business_time_normalized >= current_time_normalized:
            GLOG.WARN(f"🚦 [T+1 DECISION] DELAYING signal (business_time >= current_time)")
            if business_time_normalized > current_time_normalized:
                GLOG.CRITICAL(f"🚨 [FUTURE TIME] Individual Mode: Future signal from {event.business_timestamp} (current: {current_time}), delaying to next period.",
                )
            else:
                GLOG.INFO(f"🚦 [T+1 DELAY] Signal from {event.business_timestamp} (current: {current_time}) DELAYED to next day due to T+1 trading rule!",
                )
            self._signals.append(event.payload)
            print(
                f"[T1_DELAY] {signal_payload.direction.name} {signal_payload.code} SignalTime:{event.business_timestamp} CurrentTime:{current_time} TotalDelayed:{len(self._signals)} Portfolio:{self.uuid[:8]}"
            )
            GLOG.INFO(f"⚠️ [T+1 MECHANISM] No order will be generated today. Signal will be processed on next trading day.",
            )
            return

        # 1. Transfer signal to sizer
        GLOG.WARN(f"🎯 [SIGNAL TO ORDER] Calling sizer.cal() for signal {event.code} {event.direction}")
        portfolio_info = self.get_info()
        GLOG.WARN(f"🎯 [PORTFOLIO INFO] cash={portfolio_info.get('cash', 'N/A')}, positions={len(portfolio_info.get('positions', {}))}",
        )

        GLOG.WARN(f"🔧 [SIZER CALL] About to call sizer.cal()...")
        try:
            order = self.sizer.cal(portfolio_info, event.payload)
            # 添加Sizer结果的关键事件流日志
            if order:
                print(
                    f"[SIZED] {order.direction.name} {order.code} {order.volume}shares @ {order.limit_price} Portfolio:{self.uuid[:8]} Order:{order.uuid[:8]}"
                )
                # [订单持久化] NEW 状态持久化位置
                # SUBMITTED 状态由 TradeGateway._save_submitted_order_record() 保存
                # FILLED 状态由 on_order_partially_filled() 保存
                self._save_order_record(order, ORDERSTATUS_TYPES.NEW)
            else:
                print(
                    f"[SIZED_FAIL] {event.payload.direction.name} {event.payload.code} Reason:Sizer returned None Portfolio:{self.uuid[:8]} Signal:{event.payload.uuid[:8]}"
                )
                return
        except Exception as e:
            print(
                f"[SIZED_ERROR] {event.payload.direction.name} {event.payload.code} Error:{e} Portfolio:{self.uuid[:8]} Signal:{event.payload.uuid[:8]}"
            )
            return
        else:
            GLOG.WARN(f"✅ [ORDER GENERATED] {order.direction.name} {order.volume} shares of {order.code} @ {order.limit_price or 'MARKET'} (uuid: {order.uuid[:8]})",
            )
        GLOG.WARN(f"📋 [ORDER INFO] Generated ORDER about {order.code} {order.direction} by sizer. {self.business_timestamp}",
        )

        # 3. Transfer the order to risk_managers
        GLOG.WARN(f"🛡️ [RISK MANAGEMENT] Processing order through {len(self.risk_managers)} risk managers")
        for i, risk_manager in enumerate(self.risk_managers):
            order_before_rm = order
            order = risk_manager.cal(self.get_info(), order)
            if order is None:
                GLOG.WARN(f"⚠️ ORDER BLOCKED by risk manager #{i+1} ({risk_manager.__class__.__name__}) for {event.code}",
                )
                return
            else:
                if order_before_rm.volume != order.volume:
                    GLOG.INFO(f"📊 RISK MANAGER #{i+1} adjusted volume: {order_before_rm.volume} → {order.volume}"
                    )

        # 4. Get the adjusted order, if so put eventorder to engine
        if order is None:
            GLOG.WARN(f"ORDER about {event.code} prevent by risk manager. {self.business_timestamp}")
            return
        # Prevent Doing Zero Volume Order
        if order.volume == 0:
            GLOG.WARN(f"ORDER about {event.code} prevent by zero volume. {self.business_timestamp}")
            return
        order.frozen_money = round(order.frozen_money, 2)
        order.remain = round(order.remain, 2)
        # 若未显式设置remain，则以冻结金额为准，便于部分成交按剩余冻结处理
        if order.remain is None or to_decimal(order.remain) == 0:
            order.remain = to_decimal(order.frozen_money)

        # 5. Cash/Position freezing
        if order.direction == DIRECTION_TYPES.LONG:
            # ===== LONG SIGNAL PROCESSING START =====
            GLOG.INFO(f"🔥 [LONG SIGNAL] === START PROCESSING {event.code} ===")
            GLOG.INFO(f"🔥 [LONG SIGNAL] Portfolio BEFORE: cash={self.cash:.2f}, frozen={self.frozen:.2f}, total_available={self.cash + self.frozen:.2f}")
            GLOG.INFO(f"🔥 [LONG SIGNAL] Order details: volume={order.volume}, frozen_money={order.frozen_money:.2f}, limit_price={order.limit_price}, uuid={order.uuid[:8]}")
            GLOG.INFO(f"💰 CASH FREEZE: Attempting to freeze {order.frozen_money} for LONG order {event.code}")
            GLOG.INFO(f"💰 Current cash before freeze: {self.cash}")
            freeze_ok = self.freeze(order.frozen_money)
            if not freeze_ok:
                GLOG.WARN(f"❌ INSUFFICIENT CASH: Cannot afford ORDER about {event.code}. Need: {order.frozen_money}, Have: {self.cash}")
                GLOG.ERROR(f"🔥 [LONG SIGNAL] === FAILED PROCESSING {event.code} (INSUFFICIENT CASH) ===")
                return
            GLOG.INFO(f"✅ CASH FROZEN: {order.frozen_money}, Remaining cash: {self.cash}")
            GLOG.INFO(f"🔥 [LONG SIGNAL] Portfolio AFTER FREEZE: cash={self.cash:.2f}, frozen={self.frozen:.2f}")
            GLOG.INFO(f"🔥 [LONG SIGNAL] === SUCCESSFULLY FROZEN {event.code} ===")
            # ===== LONG SIGNAL PROCESSING END =====
        elif order.direction == DIRECTION_TYPES.SHORT:
            GLOG.INFO(f"📉 POSITION FREEZE: Attempting to freeze {order.volume} shares for SHORT order {event.code}"
            )
            if order.code not in self.positions.keys():
                GLOG.WARN(f"❌ NO POSITION: Do not have position about {order.code}. {self.business_timestamp}")
                return
            current_pos_volume = self.get_position(order.code).volume
            GLOG.INFO(f"📉 Current position: {current_pos_volume} shares, Need to freeze: {order.volume}")
            freeze_ok = self.get_position(order.code).freeze(order.volume)
            if not freeze_ok:
                GLOG.WARN(f"❌ INSUFFICIENT POSITION: Do not have enough position about {order.code}. Need: {order.volume}, Have: {current_pos_volume}")
                return
            GLOG.INFO(f"✅ POSITION FROZEN: {order.volume} shares of {event.code}")
        # 6. Create and submit order event to engine
        GLOG.INFO(f"📤 ORDER SUBMISSION: Creating EventOrderAck for {order.direction.name} {order.volume} shares of {order.code}")
        # 调试：检查引擎绑定状态
        GLOG.INFO(f"🔍 [EVENT DEBUG] Creating EventOrderAck - portfolio_id={self.uuid}, engine_id={self.engine_id}, run_id={self.run_id}")
        GLOG.INFO(f"🔍 [EVENT DEBUG] Bound engine: {self.bound_engine}, Engine ID: {self.bound_engine.engine_id if self.bound_engine else None}")

        event = EventOrderAck(order, portfolio_id=self.uuid, engine_id=self.engine_id, run_id=self.run_id)
        event.broker_order_id = f"BROKER_{order.uuid[:8]}"

        # Set the order as payload for unified access
        event.payload = order

        print(
            f"[ORDER] {order.direction.name} {order.code} {order.volume}shares @ {order.limit_price} Frozen:{order.frozen_money} Order:{order.uuid[:8]} Portfolio:{self.uuid[:8]}"
        )

        # Call analyzer hooks
        for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.ORDERSEND]:
            func(RECORDSTAGE_TYPES.ORDERSEND, self.get_info())
        for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.ORDERSEND]:
            func(RECORDSTAGE_TYPES.ORDERSEND, self.get_info())

        # Submit to engine
        GLOG.WARN(f"🚀 [ORDER TO ENGINE] Submitting order event to engine for matchmaking - Event: {event.uuid[:8] if hasattr(event, 'uuid') else 'N/A'}",
        )
        GLOG.WARN(f"📋 [EVENT DETAILS] Event type: {type(event).__name__}, Order: {event.order.code if hasattr(event, 'order') else 'N/A'}",
        )
        self.put(event)
        GLOG.WARN(f"✅ [ORDER FLOW COMPLETE] Signal → Order → Risk Management → Freezing → Engine submission")

    def on_price_received(self, event: EventPriceUpdate):
        # 🔍 [DEBUG] 追踪on_price_received调用
        event_uuid = getattr(event, "uuid", "N/A")[:8]
        event_code = getattr(event, "code", "N/A")
        event_price = getattr(event, "close", "N/A")

        # Check Everything.
        code = ""
        try:
            code = event.code
        except Exception as e:
            pass

        GLOG.INFO(f"Got new price {code if code != '' else ''}. {self.business_timestamp}")

        if not self.is_all_set():
            return

        # 0 Time check
        if self.is_event_from_future(event):
            return

        # 1. Update position price
        if event.code in self.positions:
            self.positions[event.code].on_price_update(event.close)
            self.update_worth()
            self.update_profit()

        # 2. Transfer price to each strategy
        if len(self.strategies) == 0:
            GLOG.CRITICAL(f"There is no strategy in the portfolio. Check your config. {self.business_timestamp}")
            return

        # GLOG.INFO(f"Under {len(self.strategies)} Strategies Calculating... {self.business_timestamp}")
        for strategy in self.strategies:
            # 3. Get signal return, if so put eventsignal to engine
            signals = []
            try:
                signals = strategy.cal(self.get_info(), event)

                # 防御性处理：确保signals是列表类型
                if signals is None:
                    signals = []
                elif not isinstance(signals, list):
                    # 如果返回的是单个Signal对象，包装成列表
                    if hasattr(signals, "code"):  # 简单检查是否是Signal对象
                        signals = [signals]
                        GLOG.WARN(f"Strategy {strategy.name} returned single Signal instead of List[Signal], auto-wrapped",
                        )
                    else:
                        GLOG.ERROR(f"Strategy {strategy.name} returned invalid type {type(signals)}, ignoring")
                        signals = []

            except Exception as e:
                GLOG.ERROR(f"Strategy {strategy.name} cal() failed: {e}")
                signals = []
            finally:
                pass
            # 处理每个信号
            for signal in signals:
                if signal:
                    # 🔍 调试：跟踪信号处理
                    signal_uuid = getattr(signal, "uuid", "N/A")[:8]
                    print(f"\n💼 [PORTFOLIO SIGNAL PROCESS] Portfolio UUID: {self.uuid[:8]}")
                    print(f"    Strategy Signal: {signal.direction.name} {signal.code} at {signal.business_timestamp}")
                    print(f"    Signal UUID: {signal_uuid}")
                    print(f"    Signal Reason: {signal.reason}")
                    print(f"    From Strategy: {strategy.name if strategy else 'Unknown'}")

                    # 将信号保存到数据库
                    try:
                        signal_crud = container.cruds.signal()
                        signal_crud.create(
                            portfolio_id=signal.portfolio_id,
                            engine_id=signal.engine_id,
                            run_id=signal.run_id,
                            timestamp=signal.business_timestamp,  # 使用业务时间，而不是系统时间
                            code=signal.code,
                            direction=signal.direction,
                            reason=signal.reason,
                            source=signal.source,
                            business_timestamp=signal.business_timestamp,
                        )
                        GLOG.DEBUG(f"Signal saved to database: {signal.code} {signal.direction}")
                    except Exception as e:
                        GLOG.ERROR(f"Failed to save signal to database: {e}")

                    e = EventSignalGeneration(signal)
                    e.set_source(SOURCE_TYPES.STRATEGY)
                    # 🔍 [CRITICAL] LOG: 追踪事件发布
                    event_uuid = getattr(e, "uuid", "N/A")[:8]
                    print(f"📤 [PUBLISHING] EventSignalGeneration: Event UUID={event_uuid}, Signal UUID={signal_uuid}")
                    print(f"    Event ID: {id(e)}, Signal Code: {signal.code}")
                    print(f"    From Portfolio: {self.name} (UUID: {self.uuid[:8]})")

                    for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.SIGNALGENERATION]:
                        func(RECORDSTAGE_TYPES.SIGNALGENERATION, self.get_info())
                    for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.SIGNALGENERATION]:
                        func(RECORDSTAGE_TYPES.SIGNALGENERATION, self.get_info())

                    print(f"📤 [PUTTING] EventSignalGeneration to engine: {event_uuid}")
                    self.put(e)
                    print(f"✅ [PUBLISHED] EventSignalGeneration sent to engine: {event_uuid}")

    # ===== 订单记录保存辅助方法 =====
    def _save_order_record(self, order, status, transaction_price=0, transaction_volume=0, fee=0):
        """
        保存订单记录到数据库

        Args:
            order: 订单对象
            status: 订单状态
            transaction_price: 成交价格
            transaction_volume: 成交数量
            fee: 手续费
        """
        try:
            from ginkgo.data.containers import container
            result_service = container.result_service()
            result = result_service.create_order_record(
                order_id=order.uuid,
                portfolio_id=self.uuid,
                engine_id=self.engine_id,
                run_id=self.run_id,
                code=order.code,
                direction=order.direction,
                order_type=order.order_type,
                status=status,
                volume=order.volume,
                limit_price=order.limit_price,
                frozen=order.frozen_money if hasattr(order, 'frozen_money') else 0,
                transaction_price=transaction_price,
                transaction_volume=transaction_volume,
                remain=order.remain if hasattr(order, 'remain') else 0,
                fee=fee,
                timestamp=order.timestamp,
                business_timestamp=order.business_timestamp if hasattr(order, 'business_timestamp') else order.timestamp,
            )
            print(f"[PERSISTENCE] Order record saved: code={order.code} status={status.name} price={transaction_price} vol={transaction_volume}")
            return result.success
        except Exception as e:
            print(f"[PERSISTENCE ERROR] Failed to save order record: {e}")
            GLOG.ERROR(f"Failed to save order record: {e}")
            return False

    # ===== 新增：订单生命周期事件处理（ACK/部分成交/拒绝/过期/撤销确认） =====
    # TODO: [订单持久化] SUBMITTED 状态由 TradeGateway._save_submitted_order_record() 保存
    #       ORDERACK 事件只注册给 TradeGateway，不注册给 Portfolio
    #       所以此方法不会被引擎调用，保留仅为兼容性考虑
    def on_order_ack(self, event) -> None:
        try:
            for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.ORDERACK]:
                func(RECORDSTAGE_TYPES.ORDERACK, self.get_info())
            for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.ORDERACK]:
                func(RECORDSTAGE_TYPES.ORDERACK, self.get_info())
            GLOG.INFO(f"ACK: order={event.order_id[:8]} code={event.code} msg={getattr(event, 'ack_message', '')}"
            )

            # 可选：跟踪订单
            if hasattr(self, "_orders") and event.order not in self._orders:
                self._orders.append(event.order)

        except Exception as e:
            GLOG.ERROR(f"on_order_ack failed: {e}")
            import traceback
            traceback.print_exc()

    # [订单持久化] FILLED/PARTIAL_FILLED 状态持久化位置
    # 事件由 TradeGateway.on_order_partially_filled() 路由到此处
    def on_order_partially_filled(self, event) -> None:
        try:
            if self.is_event_from_future(event):
                return
            for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.ORDERPARTIALLYFILLED]:
                func(RECORDSTAGE_TYPES.ORDERPARTIALLYFILLED, self.get_info())
            for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.ORDERPARTIALLYFILLED]:
                func(RECORDSTAGE_TYPES.ORDERPARTIALLYFILLED, self.get_info())

            order = getattr(event, "order", None)
            if order is None:
                GLOG.ERROR("Partial fill event missing order payload")
                return

            # 先从事件中获取成交信息
            qty = int(getattr(event, "filled_quantity", 0) or 0)
            price = to_decimal(getattr(event, "fill_price", 0) or 0)
            fee = to_decimal(getattr(event, "commission", 0) or 0)
            if qty <= 0 or price <= 0:
                GLOG.WARN(f"🚫 [FILL REJECTED] Partial fill ignored due to invalid qty/price: {qty}/{price}")
                GLOG.WARN(f"🚫 [FILL REJECTED] Order NOT added to filled_orders list: {order.code} {order.direction.name}",
                )
                return

            # 保存订单记录（FILLED 状态）
            self._save_order_record(order, ORDERSTATUS_TYPES.FILLED, price, qty, fee)

            # 🔥 [CRITICAL FIX] 只有在验证通过后才添加到成交订单列表
            # 🎯 订单统计更新：跟踪已成交的订单
            if order not in self._orders:
                self._orders.append(order)
                GLOG.INFO(f"📊 [ORDER TRACKING] Added filled order to tracking: {order.code} {order.direction.name} {order.volume} shares")

            # 添加到成交订单列表 (只有真实成交的订单)
            self._filled_orders.append(order)
            GLOG.INFO(f"📊 [FILLED ORDER TRACKING] Added VALID filled order: {order.code} {order.direction.name} {order.volume} shares @ {price}")

            direction = getattr(order, "direction", None) or getattr(event, "direction", None)
            code = event.code

            # 添加订单部分成交的关键事件流日志
            print(
                f"[FILL] {direction.name} {code} {qty}shares @ {price} Fee:{fee} TotalFilled:{order.transaction_volume}/{order.volume} Order:{order.uuid[:8]} Portfolio:{self.uuid[:8]}"
            )

            # 记录订单成交事件到ClickHouse
            GLOG.backtest.fill(
                order_id=order.uuid,
                price=price,
                volume=qty,
                commission=fee,
                symbol=code,
                direction=direction.value if hasattr(direction, 'value') else str(direction),
                portfolio_id=self.uuid,
                engine_id=self.engine_id,
                run_id=self.run_id,
            )

            fill_cost = price * qty + fee

            # 更新订单累计成交与剩余冻结
            try:
                order.transaction_volume = min(order.volume, order.transaction_volume + qty)
            except Exception as e:
                GLOG.ERROR(f"Failed to update transaction_volume: {e}")

            if not hasattr(order, "remain") or order.remain is None:
                order.remain = order.frozen_money
            order.remain = to_decimal(order.remain)
            order.remain = max(Decimal("0"), order.remain - fill_cost)

            is_final = (
                getattr(event, "order_status", None) == ORDERSTATUS_TYPES.FILLED
                or order.transaction_volume >= order.volume
            )

            # LONG 部分成交：从冻结资金扣除成交成本，根据是否最终成交决定是否释放剩余资金
            if direction == DIRECTION_TYPES.LONG:
                GLOG.INFO(f"🔍 [PARTIAL FILL] BEFORE: UUID={order.uuid[:8] if hasattr(order, 'uuid') else 'NO_UUID'}, order.remain={order.remain:.2f}, self.frozen={self.frozen:.2f}, fill_cost={fill_cost:.2f}, is_final={is_final}",
                )

                # 如果不是最终成交，不解冻剩余资金；如果是最终成交，解冻所有剩余资金
                unfreeze_remain = order.remain if is_final else Decimal("0")

                # 从冻结资金中扣除成交成本
                self.deduct_from_frozen(cost=fill_cost, unfreeze_remain=unfreeze_remain)

                # 同步更新订单的剩余冻结金额
                order.remain = max(Decimal("0"), order.remain - fill_cost)
                if is_final:
                    order.remain = Decimal("0")

                GLOG.INFO(f"🔍 [PARTIAL FILL] AFTER: order={order.uuid[:8]}, order.remain={order.remain:.2f}, self.frozen={self.frozen:.2f}",
                )
                self.add_fee(fee)

                pos = self.get_position(code)
                if pos is None:
                    p = Position(
                        portfolio_id=self.uuid,
                        engine_id=self.engine_id,
                        run_id=self.run_id,
                        code=code,
                        cost=price,
                        volume=qty,
                        price=price,
                        frozen=0,
                        fee=fee,
                        uuid=uuid.uuid4().hex,
                    )
                    self.add_position(p)
                    # 添加Position创建的关键事件流日志
                    print(
                        f"[POSITION] LONG {code} {qty}shares @ {price} Fee:{fee} Portfolio:{self.uuid[:8]} Position:{p.uuid[:8]}"
                    )
                else:
                    pos.deal(DIRECTION_TYPES.LONG, price, qty)
                    # 添加Position更新的关键事件流日志
                    print(
                        f"[POSITION] LONG {code} +{qty}shares @ {price} Total:{pos.volume} Portfolio:{self.uuid[:8]} Position:{pos.uuid[:8]}"
                    )

                GLOG.INFO(f"PARTIAL LONG filled {code}: {qty}@{price}, fee={fee}, remain_frozen={order.remain}",
                )

            # SHORT 部分成交：入账现金（成交额-手续费），已冻结仓位随成交递减，剩余冻结保持
            elif direction == DIRECTION_TYPES.SHORT:
                proceeds = price * qty - fee
                self.add_cash(proceeds)
                self.add_fee(fee)

                pos = self.get_position(code)
                if pos is None:
                    GLOG.ERROR(f"Partial SHORT fill but no position found for {code}")
                else:
                    pos.deal(DIRECTION_TYPES.SHORT, price, qty)
                    self.clean_positions()

                GLOG.INFO(f"PARTIAL SHORT filled {code}: {qty}@{price}, fee={fee}")
            else:
                GLOG.WARN(f"Partial fill with unknown direction for {code}")

            # 更新组合指标
            self.update_worth()
            self.update_profit()

        except Exception as e:
            GLOG.ERROR(f"on_order_partially_filled failed: {e}")
            import traceback

            GLOG.ERROR(f"on_order_partially_filled traceback: {traceback.format_exc()}")

    # [订单持久化] REJECTED 状态持久化位置
    # 事件由 engine_assembly_service.py:1562 直接注册到 Portfolio
    def on_order_rejected(self, event) -> None:
        try:
            for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.ORDERREJECTED]:
                func(RECORDSTAGE_TYPES.ORDERREJECTED, self.get_info())
            for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.ORDERREJECTED]:
                func(RECORDSTAGE_TYPES.ORDERREJECTED, self.get_info())
            GLOG.WARN(f"REJECTED: order={event.order_id[:8]} code={event.code} reason={event.reject_reason}")
            # 添加订单拒绝的关键事件流日志
            print(
                f"[REJECT] {getattr(event.order, 'direction', 'UNKNOWN').name} {event.code} Reason:{event.reject_reason} Order:{event.order_id[:8]} Portfolio:{self.uuid[:8]}"
            )

            # 记录订单拒绝事件到ClickHouse
            reject_code = getattr(event, "reject_code", "REJECTED")
            reject_reason = getattr(event, "reject_reason", "Unknown reason")
            GLOG.backtest.order.reject(
                order_id=event.order_id,
                code=reject_code,
                reason=reject_reason,
                portfolio_id=self.uuid,
                engine_id=self.engine_id,
                run_id=self.run_id,
            )

            # 保存订单记录（REJECTED 状态）
            order = getattr(event, "order", None)
            if order:
                self._save_order_record(order, ORDERSTATUS_TYPES.REJECTED)

        except Exception as e:
            GLOG.ERROR(f"on_order_rejected failed: {e}")

    # TODO: [订单持久化] EXPIRED 状态缺少订单记录持久化
    #       需要添加: self._save_order_record(order, ORDERSTATUS_TYPES.EXPIRED)
    #       注意：过期一般伴随取消事件，可能需要去重处理
    def on_order_expired(self, event) -> None:
        try:
            for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.ORDEREXPIRED]:
                func(RECORDSTAGE_TYPES.ORDEREXPIRED, self.get_info())
            for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.ORDEREXPIRED]:
                func(RECORDSTAGE_TYPES.ORDEREXPIRED, self.get_info())
            GLOG.WARN(f"EXPIRED: order={event.order_id[:8]} code={event.code} reason={event.expire_reason}")

            # 记录订单过期事件到ClickHouse
            expire_reason = getattr(event, "expire_reason", "Unknown reason")
            expired_quantity = getattr(event, "expired_quantity", 0)
            order_id = getattr(event, "order_id", "")
            order = getattr(event, "order", None)
            if order:
                order_id = order_id or order.uuid

            GLOG.backtest.order.expire(
                order_id=order_id,
                reason=expire_reason,
                expired_quantity=expired_quantity,
                portfolio_id=self.uuid,
                engine_id=self.engine_id,
                run_id=self.run_id,
            )

            # 过期一般伴随取消事件；组合在取消事件中做资金/仓位回滚
        except Exception as e:
            GLOG.ERROR(f"on_order_expired failed: {e}")


    # [订单持久化] CANCELED 状态持久化位置
    # 事件由 engine_assembly_service.py:1559 直接注册到 Portfolio
    def on_order_cancel_ack(self, event) -> None:
        try:
            GLOG.INFO(f"Got An Order Cancelled... {self.business_timestamp}")
            # 处理ORDERCANCELED阶段的hooks
            for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.ORDERCANCELED]:
                func(RECORDSTAGE_TYPES.ORDERCANCELED, self.get_info())
            for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.ORDERCANCELED]:
                func(RECORDSTAGE_TYPES.ORDERCANCELED, self.get_info())

            # 处理ORDERCANCELACK阶段的hooks
            for func in self._analyzer_activate_hook[RECORDSTAGE_TYPES.ORDERCANCELACK]:
                func(RECORDSTAGE_TYPES.ORDERCANCELACK, self.get_info())
            for func in self._analyzer_record_hook[RECORDSTAGE_TYPES.ORDERCANCELACK]:
                func(RECORDSTAGE_TYPES.ORDERCANCELACK, self.get_info())

            GLOG.WARN(f"Dealing with CANCELED ORDER. {self.business_timestamp}")
            if self.is_event_from_future(event):
                return

            order = getattr(event, "order", None)

            # 记录订单取消事件到ClickHouse
            cancel_reason = getattr(event, "cancel_reason", "User cancelled")
            cancelled_quantity = getattr(event, "cancelled_quantity", 0)
            order_id = getattr(event, "order_id", "")
            if order:
                order_id = order_id or order.uuid

            GLOG.backtest.order.cancel(
                order_id=order_id,
                reason=cancel_reason,
                cancelled_quantity=cancelled_quantity,
                portfolio_id=self.uuid,
                engine_id=self.engine_id,
                run_id=self.run_id,
            )

            # 保存订单记录（CANCELED 状态）
            if order:
                self._save_order_record(order, ORDERSTATUS_TYPES.CANCELED)

            direction = getattr(event, "direction", None) or (order.direction if hasattr(order, "direction") else None)

            if direction == DIRECTION_TYPES.LONG:
                remain = None
                if order is not None:
                    remain = getattr(order, "remain", None)
                    if remain is None:
                        remain = getattr(order, "frozen_money", 0)
                if remain is None:
                    GLOG.ERROR(f"Cancel event missing remain for {event.code}")
                    return
                remain = to_decimal(remain)
                if remain > 0:
                    self.unfreeze(remain)
                    if order is not None:
                        order.remain = Decimal("0")
                GLOG.INFO(f"Dealing ORDER about {event.code} CANCELED. unfrozen cash {remain} {self.business_timestamp}",
                )
            elif direction == DIRECTION_TYPES.SHORT:
                code = event.code
                pos = self.positions.get(code)
                cancel_vol = int(getattr(event, "cancelled_quantity", 0) or 0)
                if pos is None:
                    GLOG.ERROR(f"Cancel SHORT but position missing for {code}")
                else:
                    if cancel_vol > 0:
                        pos.unfreeze(cancel_vol)
                GLOG.WARN(f"DONE UNFREEZE SHORT. {self.business_timestamp}")

            GLOG.INFO(f"CANCEL-ACK: order={getattr(event, 'order_id', 'N/A')[:8]} code={event.code} cancelled_qty={getattr(event, 'cancelled_quantity', 'N/A')}",
            )
            self.update_worth()
            self.update_profit()

        except Exception as e:
            GLOG.ERROR(f"on_order_cancel_ack failed: {e}")

    def on_order_filled(self, event) -> None:
        """订单完全成交事件处理器 - 特殊的partially_filled (remain=0)"""
        try:
            # 触发分析器记录
            for func in self._analyzer_activate_hook.get(RECORDSTAGE_TYPES.ORDERFILLED, []):
                func(RECORDSTAGE_TYPES.ORDERFILLED, self.get_info())
            for func in self._analyzer_record_hook.get(RECORDSTAGE_TYPES.ORDERFILLED, []):
                func(RECORDSTAGE_TYPES.ORDERFILLED, self.get_info())

            GLOG.INFO(f"Portfolio {self.name}: Order completely filled")

            # 委托给现有的部分成交处理器，复用所有现有逻辑
            # ORDERFILLED本质上是remain=0的特殊ORDERPARTIALLYFILLED
            self.on_order_partially_filled(event)
        except Exception as e:
            GLOG.ERROR(f"on_order_filled failed: {e}")

    def deal_long_filled(self, event: EventOrderPartiallyFilled, *args, **kwargs):
        # ===== LONG ORDER FILLED START =====
        GLOG.INFO(f"💰 [LONG FILLED] === START PROCESSING FILLED ORDER {event.code} ===")
        GLOG.INFO(f"💰 [LONG FILLED] Portfolio BEFORE UNFREEZE: cash={self.cash:.2f}, frozen={self.frozen:.2f}")
        GLOG.INFO(f"💰 [LONG FILLED] Event details: code={event.code}, transaction_volume={event.transaction_volume}, transaction_price={event.transaction_price:.2f}",
        )
        GLOG.INFO(f"💰 [LONG FILLED] Financial details: frozen={event.frozen:.2f}, remain={event.remain:.2f}, fee={event.fee:.2f}")

        if self.frozen < event.frozen:
            GLOG.CRITICAL(f"Over flow, can not unfreeze {event.frozen} from {self.frozen}. {self.business_timestamp}")
            GLOG.ERROR(f"💰 [LONG FILLED] === FAILED PROCESSING {event.code} (OVERFLOW) ===")
            return
        if event.remain < 0:
            GLOG.CRITICAL(f"Order can not remain under 0.")
            GLOG.ERROR(f"💰 [LONG FILLED] === FAILED PROCESSING {event.code} (NEGATIVE REMAIN) ===")
            return

        # 🚨 重要修复：使用新的deduct_from_frozen方法正确处理部分成交
        transaction_cost = event.frozen - event.remain
        GLOG.INFO(f"🔍 [LONG FILLED] Transaction cost: ${transaction_cost:.2f} (converted to Position)")
        GLOG.INFO(f"🔍 [LONG FILLED] Unfreezing remaining unfilled amount: ${event.remain:.2f}")
        GLOG.INFO(f"🔍 [LONG FILLED] Event details: original_frozen={event.frozen:.2f}, remain={event.remain:.2f}, transaction_cost={transaction_cost:.2f}",
        )

        # 使用新的公共方法：扣除成交花费，只将剩余未成交部分解冻
        self.deduct_from_frozen(cost=transaction_cost, unfreeze_remain=event.remain)

        GLOG.INFO(f"💰 [LONG FILLED] Processed transaction cost {transaction_cost:.2f} and unfroze remain {event.remain:.2f}")
        GLOG.INFO(f"💰 [LONG FILLED] Portfolio AFTER: cash={self.cash:.2f}, frozen={self.frozen:.2f}")

        self.add_fee(event.fee)
        GLOG.INFO(f"💰 [LONG FILLED] Added fee: {event.fee:.2f}, New cash: {self.cash:.2f}")

        p = Position(
            portfolio_id=self.uuid,
            engine_id=self.engine_id,
            run_id=self.run_id,
            code=event.code,
            cost=event.transaction_price,
            volume=event.transaction_volume,
            price=event.transaction_price,
            frozen=0,
            fee=event.fee,
            uuid=uuid.uuid4().hex,
        )
        self.add_position(p)
        GLOG.INFO(f"💰 [LONG FILLED] Created position: {event.code}, volume={event.transaction_volume}, cost={event.transaction_price:.2f}",
        )

        # 🎯 成交订单统计更新 - 已在on_order_partially_filled方法中处理，此处避免重复统计

        position_count = len(self.positions)
        total_position_value = sum(pos.worth for pos in self.positions.values() if hasattr(pos, "worth"))
        GLOG.INFO(f"💰 [LONG FILLED] Portfolio SUMMARY: cash={self.cash:.2f}, frozen={self.frozen:.2f}, positions={position_count}, total_position_worth={total_position_value:.2f}",
        )

        # 记录资金更新事件到ClickHouse
        try:
            total_value = self.cash + self.frozen + total_position_value
            GLOG.backtest.trade.capital(
                total=total_value,
                cash=self.cash,
                frozen_cash=self.frozen,
                portfolio_id=self.uuid,
                engine_id=self.engine_id,
                run_id=self.run_id,
                business_timestamp=self.business_timestamp,
            )
        except Exception as e:
            GLOG.ERROR(f"Failed to log capital event: {e}")

        GLOG.WARN(f"Fill a LONG ORDER DONE. {self.business_timestamp}")
        GLOG.INFO(f"💰 [LONG FILLED] === SUCCESSFULLY PROCESSED FILLED ORDER {event.code} ===")
        # ===== LONG ORDER FILLED END =====

    def deal_short_filled(self, event: EventOrderPartiallyFilled, *args, **kwargs):
        if event.remain < 0:
            GLOG.CRITICAL(f"Order can not remain under 0.")
            return
        if event.code not in self.positions.keys():
            GLOG.CRITICAL(f"Can not handler the short order about no exist {event.code}. {self.business_timestamp}")
            return
        if event.transaction_volume > self.positions[event.code].frozen_volume:
            GLOG.CRITICAL(f"Can not handler the short order about over flow. {self.business_timestamp}")
            return
        # 🚨 修复：不应该添加event.remain，因为这部分资金应该已经通过unfreeze正确处理了
        # self.add_cash(event.remain)  # 已注释掉，这是导致资金重复计算的错误
        GLOG.INFO(f"💰 [SHORT FILLED] Fixed: NOT adding remain cash {event.remain:.2f} (already handled by unfreeze). {self.business_timestamp}")
        self.add_fee(event.fee)
        self.positions[event.code].deal(DIRECTION_TYPES.SHORT, event.transaction_price, event.transaction_volume)
        self.clean_positions()

        # 记录资金更新事件到ClickHouse
        try:
            total_value = self.cash + self.frozen + sum(
                pos.worth for pos in self.positions.values() if hasattr(pos, "worth")
            )
            GLOG.backtest.trade.capital(
                total=total_value,
                cash=self.cash,
                frozen_cash=self.frozen,
                portfolio_id=self.uuid,
                engine_id=self.engine_id,
                run_id=self.run_id,
                business_timestamp=self.business_timestamp,
            )
        except Exception as e:
            GLOG.ERROR(f"Failed to log capital event: {e}")

        GLOG.WARN(f"Fill a SHORT ORDER DONE. {self.business_timestamp}")

    def __repr__(self) -> str:
        """安全的__repr__实现，避免循环递归导致的性能问题"""
        try:
            # 基本信息，避免访问可能引起递归的属性
            cash = float(self.cash) if hasattr(self, "cash") else 0.0
            frozen = float(self.frozen) if hasattr(self, "frozen") else 0.0
            worth = float(self.worth) if hasattr(self, "worth") else 0.0
            position_count = len(self.positions) if hasattr(self, "positions") else 0
            strategy_count = len(self._strategies) if hasattr(self, "_strategies") else 0

            return (
                f"{PortfolioT1Backtest.__name__}(\n"
                f"  name: {getattr(self, 'name', 'Unknown')}\n"
                f"  uuid: {getattr(self, 'uuid', 'Unknown')[:8]}...\n"
                f"  cash: {cash:,.2f}\n"
                f"  frozen: {frozen:,.2f}\n"
                f"  worth: {worth:,.2f}\n"
                f"  positions: {position_count}\n"
                f"  strategies: {strategy_count}\n"
                f"  time: {getattr(self, 'business_timestamp', 'N/A')}\n"
                f")"
            )
        except Exception:
            # 异常时返回最简信息
            return f"{PortfolioT1Backtest.__name__}(name={getattr(self, 'name', 'Unknown')})"
