# yaml 配置实例
version: '3'
services:
  Mongo:
    image: mongo:latest
    container_name: ginkgo_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: caonima123
      MONGO_INITDB_DATABASE: quant
    volumes:
      # - ./mongo:/data/db
      - ./config/mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js
    networks:
      - nets
    ports:
      - "27017:27017"

  Clickhouse:
    image: yandex/clickhouse-server
    container_name: ginkgo_clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    networks:
      - nets
    volumes:
      - ./config/clickhouse_users.xml:/etc/clickhouse-server/users.xml
    ulimits:
      nproc: 65546
      nofile:
        soft: 262144
        hard: 262144

  # Agent:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: ginkgo_agent
  #   container_name: ginkgo_agent
  #   networks:
  #     - nets
networks: 
  nets:
    external: false
