# yaml 配置实例
version: '3'
services:
  # Mongo:
  #   image: mongo:latest
  #   container_name: ginkgo_mongo
  #   restart: always
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: caonima123
  #     MONGO_INITDB_DATABASE: quant
  #   volumes:
  #     - ../db/mongo:/data/db:rw
  #     - ./mongo_init.js:/docker-entrypoint-initdb.d/mongo_init.js
  #   networks:
  #     - nets
  #   ports:
  #     - "27017:27017"

  Clickhouse:
    image: clickhouse/clickhouse-server
    container_name: ginkgo_clickhouse
    restart: always
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    # networks:
    #   - nets
    volumes:
      - ../logs/clickhouse:/var/log/clickhouse-server
      - ./clickhouse_users.xml:/etc/clickhouse-server/users.xml
      - ../db/clickhouse:/var/lib/clickhouse:rw
    ulimits:
      nproc: 65546
      nofile:
        soft: 262144
        hard: 262144

    environment:
      CLICKHOUSE_DB: ginkgo
      SHOW: 'ture'
  # Agent:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   image: ginkgo_agent
  #   container_name: ginkgo_agent
  #   networks:
  #     - nets
# networks: 
#   nets:
#     external: false
