"""
The `Portfolio` class is responsible for managing the positions and capital for the system.(Backtest and Live)

- Initializing the portfolio with an initial capital amount and a set of securities to track.

- Keeping track of the current positions and cash balance for the portfolio.

- Executing trades based on signals generated by the Strategy.

- Generating reports and metrics related to the performance of the portfolio. The reports also contain charts.
"""
from ginkgo.backtest.portfolios.base_portfolio import BasePortfolio
from ginkgo.backtest.bar import Bar
from ginkgo.libs.ginkgo_logger import GLOG
from ginkgo.backtest.events import (
    EventOrderSubmitted,
    EventOrderFilled,
    EventSignalGeneration,
    EventPriceUpdate,
    EventOrderCanceled,
    EventNextPhase,
)
from ginkgo.data.ginkgo_data import GDATA
from ginkgo.data.models import MOrder
from ginkgo.libs import GinkgoSingleLinkedList, datetime_normalize
from src.ginkgo.notifier.ginkgo_notifier import GNOTIFIER
from ginkgo.backtest.signal import Signal
from ginkgo.enums import (
    DIRECTION_TYPES,
    SOURCE_TYPES,
    ORDERSTATUS_TYPES,
    RECORDSTAGE_TYPES,
)
from ginkgo.libs.ginkgo_pretty import base_repr
from ginkgo.backtest.position import Position
from rich.console import Console
import time

console = Console()


class PortfolioLive(BasePortfolio):
    # The class with this __abstract__  will rebuild the class from bytes.
    # If not run time function will pass the class.
    __abstract__ = False

    def __init__(self, *args, **kwargs):
        super(PortfolioLive, self).__init__(*args, **kwargs)
        self._signals = GinkgoSingleLinkedList()
        self._suggestions = GinkgoSingleLinkedList()

    def recover_positions(self):
        # backtest_id = self.backtest_id
        # portfolio_id = self.uuid
        # TODO Get Positions via backtest_id and portfolio_id
        self._positions = {}

    @property
    def signals(self):
        return self._signals

    @property
    def suggestions(self):
        return self._suggestions

    def get_position(self, code: str):
        if code in self.positions.keys():
            return self.positions[code]
        return None

    def cal_suggestions(self):
        pass

    def on_time_goes_by(self, time: any, *args, **kwargs):
        """
        Go next frame.
        """
        # Time goes
        super(PortfolioLive, self).on_time_goes_by(time, *args, **kwargs)
        self.update_worth()
        self.update_profit()

    def on_signal(self, event: EventSignalGeneration):
        """
        Dealing with the signal coming.
        1. get a signal
        2. after sizer and risk manager
        3.1 drop the signal
        3.2 put order to event engine
        """
        self.record(RECORDSTAGE_TYPES.SIGNALGENERATION)
        self._signal_get_count += 1  # Record
        GLOG.INFO(
            f"{self.name} got a {event.direction} signal about {event.code}  --> {event.direction}."
        )
        # Check Everything.
        if not self.is_all_set():
            self.try_go_next_phase()
            return

        if event.timestamp > self.now:
            GLOG.WARN(
                f"Current time is {self.now.strftime('%Y-%m-%d %H:%M:%S')}, The EventSignal generated at {event.timestamp}, Can not handle the future infomation."
            )
            self._signal_passed_count += 1
            self.try_go_next_phase()
            return

        # T+1, Order will send after 1 day that signal comes.
        if event.timestamp == self.now:
            GLOG.INFO(
                f"T+1 Portfolio can not send the order generated from the signal today {event.timestamp}, we will send the order tomorrow"
            )
            self.signals.append(event.value)
            self._signal_tomorrow_count += 1
            self.try_go_next_phase()
            return

        # if the signal from past , and the stock has no price today, put it back to to_send signals.
        if not self.engine.datafeeder.is_code_on_market(event.code, self.now):
            self.signals.append(event.value)
            self._signal_tomorrow_count += 1
            self.try_go_next_phase()
            return

        # 1. Transfer signal to sizer
        order = self.sizer.cal(event.value)
        # 2. Get the order return
        if order is None:
            self._signal_passed_count += 1
            self.try_go_next_phase()
            return

        # 3. Transfer the order to risk_manager
        order_adjusted = self.risk_manager.cal(order)

        # 4. Get the adjusted order, if so put eventorder to engine
        if order_adjusted is None:
            self._signal_passed_count += 1
            self.try_go_next_phase()
            return

        if order_adjusted.volume == 0:
            self._signal_passed_count += 1
            self.try_go_next_phase()
            return

        # 5. Create order, stored into db
        mo = MOrder()
        if order_adjusted.direction == DIRECTION_TYPES.LONG:
            GLOG.WARN("Got a LONG ORDER")
            freeze_ok = self.freeze(order_adjusted.frozen)
            GLOG.WARN("Got a LONG ORDER  After freeze")
            if not freeze_ok:
                self._signal_passed_count += 1
                self.try_go_next_phase()
                return
            mo.set(
                order_adjusted.uuid,
                order_adjusted.code,
                order_adjusted.direction,
                order_adjusted.type,
                order_adjusted.status,
                order_adjusted.volume,
                order_adjusted.limit_price,
                order_adjusted.frozen,
                order_adjusted.transaction_price,
                order_adjusted.remain,
                order_adjusted.fee,
                self.now,
                self.engine.backtest_id,
            )
            GDATA.add(mo)
            self._signal_gen_order_count += 1

            # 6. Create Event
            e = EventOrderSubmitted(order_adjusted.uuid)
            GNOTIFIER.beep()
            GLOG.INFO("Gen an Event Order Submitted...")
            self.put(e)
            self.record(RECORDSTAGE_TYPES.ORDERSEND)
            self._order_send_count += 1  # Record
            GLOG.WARN(f"Send : {self._order_send_count}")

        elif order_adjusted.direction == DIRECTION_TYPES.SHORT:
            GLOG.WARN("Got a SHORT ORDER")
            pos = self.get_position(order_adjusted.code)
            volume_freezed = pos.freeze(order_adjusted.volume)
            GLOG.WARN("Got a SHORT ORDER Done..")
            mo.set(
                order_adjusted.uuid,
                order_adjusted.code,
                order_adjusted.direction,
                order_adjusted.type,
                order_adjusted.status,
                volume_freezed,
                order_adjusted.limit_price,
                order_adjusted.frozen,
                order_adjusted.transaction_price,
                order_adjusted.remain,
                order_adjusted.fee,
                self.now,
                self.engine.backtest_id,
            )
            GLOG.WARN("Send a Short ORDER.")
            GDATA.add(mo)
            self._signal_gen_order_count += 1
            e = EventOrderSubmitted(order_adjusted.uuid)
            GNOTIFIER.beep()
            # 6. Create Event
            self.put(e)
            self.record(RECORDSTAGE_TYPES.ORDERSEND)
            self.orders.append(order_adjusted.uuid)  # Seems not work.
            self._order_send_count += 1  # Record

            GLOG.WARN(f"Send : {self._order_send_count}")
        self.try_go_next_phase()

    def on_price_update(self, event: EventPriceUpdate):
        self._price_get_count += 1  # Record

        # Check Everything.
        if not self.is_all_set():
            self.try_go_next_phase()
            return

        # 0 Time check
        if event.timestamp > self.now:
            GLOG.WARN(
                f"Current time is {self.now.strftime('%Y-%m-%d %H:%M:%S')}, The EventPriceUpdate generated at {event.timestamp}, Can not handle the future infomation."
            )
            self._price_passed_count += 1
            self.try_go_next_phase()
            return

        # 1. Update position price
        if event.code in self.positions:
            self.positions[event.code].on_price_update(event.close)

        # 2. Transfer price to each strategy
        if len(self.strategies) <= 0:
            self._price_passed_count += 1
            self.try_go_next_phase()
            return

        # GLOG.INFO(f"Under {len(self.strategies)} Strategies Calculating... {self.now}")
        for strategy in self.strategies:
            # 3. Get signal return, if so put eventsignal to engine
            signal = strategy.value.cal(event.value)
            if signal:
                e = EventSignalGeneration(signal)
                e.set_source(SOURCE_TYPES.PORTFOLIO)
                GDATA.add_signal(
                    self.backtest_id,
                    self.now,
                    e.code,
                    e.direction,
                    f"{strategy.value.name} gen.",
                )
                self.put(e)
                self._price_gen_signal_count += 1  # Record
        # GLOG.INFO(f"Strategies Calculating Complete. {self.now}")
        self.update_worth()
        self.update_profit()
        self.try_go_next_phase()

    def on_order_filled(self, event: EventOrderFilled):
        GLOG.INFO("Got An Order Filled...")
        if not event.order_status == ORDERSTATUS_TYPES.FILLED:
            GLOG.CRITICAL(
                f"On Order Filled only handle the FILLEDORDER, cant handle a {event.order_status} one. Check the Code"
            )
            self.try_go_next_phase()
            return
        self.record(RECORDSTAGE_TYPES.ORDERFILLED)
        GDATA.add_order_record(
            self.backtest_id,
            event.value.code,
            event.value.direction,
            event.value.type,
            event.value.transaction_price,
            event.value.volume,
            event.value.remain,
            event.value.fee,
            self.now,
        )
        if event.direction == DIRECTION_TYPES.LONG:
            GLOG.WARN("DEALING with LONG FILLED ORDER")
            print(event.value)
            self.unfreeze(event.frozen)
            self.add_found(event.remain)
            self.add_fee(event.fee)
            p = Position(
                code=event.code, price=event.transaction_price, volume=event.volume
            )
            self.add_position(p)
            GLOG.WARN("Fill a LONG ORDER DONE")
        elif event.direction == DIRECTION_TYPES.SHORT:
            GLOG.WARN("DEALING with SHORT FILLED ORDER")
            self.add_found(event.remain)
            self.add_fee(event.fee)
            self.positions[event.code].deal(
                DIRECTION_TYPES.SHORT, event.transaction_price, event.volume
            )
            self.clean_positions()
            GLOG.WARN("Fill a SHORT ORDER DONE")
        GLOG.INFO("Got An Order Filled Done")
        self._order_filled_count += 1  # Record
        self.update_worth()
        self.update_profit()
        self.try_go_next_phase()

    def __repr__(self) -> str:
        return base_repr(self, PortfolioT1Backtest.__name__, 24, 60)
