heart_beat: .01
dev_mode: True

# 开发/生产环境下相同的配置
debug: True
token_expiration: 14  # Token过期时间（天）

# 日志设置
log_path: ./logs/
log_file_on: true
log_default_file: test.log
log_level_console: DEBUG
log_level_file: DEBUG
log_color: 
  DEBUG: white
  INFO: green
  WARNING: yellow
  ERROR: red
  CRITICAL: bold_red

# DB
db_driver: clickhouse
