database:
  clickhouse:
    database: ginkgo
    username: ginkgoadm
    password: aGVsbG9jbGlja2hvdXNl
    host: localhost
    port: 8123
  mongodb:
    database: ginkgo
    username: ginkgoadm
    password: aGVsbG9tb25nbw==
