
export const API_ENDPOINTS = {
  fetchBacktest: `/api/backtest`,
  delBacktest: `/api/del_backtest`,
  fetchRecord: `/api/record`,
  fetchAnalyzer: `/api/analyzer`,
  fetchOrder: `/api/order`,
  fetchOrderFilled: `/api/order_filled`,
  fetchSignal: `/api/signal`,
  fetchStockInfo: `/api/stockinfo`,
  fetchDaybar: `/api/daybar`,
  fetchFileList: `/api/file_list`,
  fetchFile: `/api/file`,
  updateFile: `/api/update_file`,
  renameFile: `/api/rename_file`,
  delFile: `/api/del_file`,
  addLivePortfolio: `/api/add_liveportfolio`,
  fetchLivePortfolio: `/api/liveportfolio`,
  delLivePortfolio: `/api/del_liveportfolio`,
  fetchCodeList: `/api/code_list`,
  fetchTradeRecord: `/api/traderecord`,
  fetchLivePositions: `/api/live_position`,
  resetLivePositions: `/api/reset_liveposition`,
  addTradeRecord: `/api/add_traderecord`,
  updateTradeRecord: `/api/update_traderecord`,
  delTradeRecord: `/api/del_traderecord`,
  sseLiveStatus: `/stream/live_status`,
  LiveControl: `/api/live_control`
}
